package com.example.wbdvsp2102YinglunYinserverjava.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="widgets")
public class Widget {

  @Id // mark as primary key
  @GeneratedValue(strategy = GenerationType.IDENTITY) // this value will be generated by database
  private Long _id;

  private String name;
  private String type;
  private String topicId;
  private Integer size;
  private String text;
  private Integer width;
  private Integer height;
  private String cssClass;
  private Integer widgetOrder;
  private String style;
  private String value;
  private String src;
  private String url;
  private String href;

  public Widget(String name, Long _id, String type, String topicId, Integer widgetOrder, Integer size, String text, Integer width, Integer height, String cssClass, String style, String value, String src, String url, String href) {
    this.name = name;
    this._id = _id;
    this.type = type;
    this.topicId = topicId;
    this.widgetOrder = widgetOrder;
    this.size = size;
    this.text = text;
    this.width = width;
    this.height = height;
    this.cssClass = cssClass;
    this.style = style;
    this.value = value;
    this.src = src;
    this.url = url;
    this.href = href;
  }

  public Widget(Long _id, String topicId, String type, Integer size, String text) {
    this._id = _id;
    this.type = type;
    this.topicId = topicId;
    this.size = size;
    this.text = text;
  }

  public Widget() {
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Long get_id() {
    return _id;
  }

  public void set_id(Long _id) {
    this._id = _id;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getTopicId() {
    return topicId;
  }

  public void setTopicId(String topicId) {
    this.topicId = topicId;
  }

  public Integer getWidgetOrder() {
    return widgetOrder;
  }

  public void setWidgetOrder(Integer widgetOrder) {
    this.widgetOrder = widgetOrder;
  }

  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public String getCssClass() {
    return cssClass;
  }

  public void setCssClass(String cssClass) {
    this.cssClass = cssClass;
  }

  public String getStyle() {
    return style;
  }

  public void setStyle(String style) {
    this.style = style;
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public String getSrc() {
    return src;
  }

  public void setSrc(String src) {
    this.src = src;
  }

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }
}
